class LocalizedResponses {
  static Map<String, Map<String, String>> responses = {
    'en': {
      'initialGreeting': 'Hello! Press the mic or shake your phone to speak.',
      'listening': 'Listening...',
      'processing': 'Processing...',
      'didntHear': 'I didn\'t hear anything.',
      'microphoneError': 'Microphone error or permission denied.',
      'cancelled': 'Okay, cancelled.',
      'yesNoPrompt': 'Please say Yes or No. Do you want to proceed?',
      'greeting1': 'Yes? How can I help you?',
      'greeting2': 'I\'m listening. What do you need?',
      'greeting3': 'Yes, tell me what you want to do.',
      'greeting4': 'I\'m here. How can I assist you?',
      'greeting5': 'What can I do for you?',
      'greeting6': 'Yes, go ahead.',
      'greeting7': 'Listening. What would you like me to do?',
      'callConfirm': 'Calling {name}.',
      'callSuccess': 'Called {name}.',
      'callFailed': 'Sorry, I couldn\'t call {name}.',
      'messageSent': 'Message sent to {name}.',
      'messageFailed': 'Sorry, I couldn\'t send the message.',
      'alarmSet': 'Alarm set for {time} {date}.',
      'alarmFailed': 'Sorry, I couldn\'t set the alarm.',
      'reminderSet': 'Reminder set for {title} at {time} {date}.',
      'reminderFailed': 'Sorry, I couldn\'t set the reminder.',
      'eventAdded': 'Event added: {title} at {time} {date}.',
      'eventDeleted': 'Event deleted for {date}.',
      'timeNow': 'The time is {time}.',
      'scheduleToday': 'You have {count} events today.',
      'nextMeeting': 'Your next meeting is {title} at {time}.',
      'noEvents': 'No events found.',
      'navigation': 'Opening {screen}.',
      'unknownCommand': 'I didn\'t understand that command.',
      'askContactName': 'Who do you want to call?',
      'askMessageText': 'What message should I send?',
      'askTime': 'What time should I set it for?',
      'askTitle': 'What should I remind you about?',
    },
    'ur': {
      'initialGreeting': 'السلام علیکم! مائیکرو دبائیں یا اپنے فون کو ہلائیں بولنے کے لیے۔',
      'listening': 'سن رہا ہے...',
      'processing': 'پروسیس ہو رہا ہے...',
      'didntHear': 'میں کچھ نہیں سنا۔',
      'microphoneError': 'مائیکروفون میں خرابی یا اجازت نہیں دی گئی۔',
      'cancelled': 'ٹھیک ہے، منسوخ کر دیا گیا۔',
      'yesNoPrompt': 'براہ کرم ہاں یا نہیں کہیں۔ کیا آپ آگے بڑھنا چاہتے ہیں؟',
      'greeting1': 'جی؟ میں آپ کی کیا مدد کر سکتا ہوں؟',
      'greeting2': 'میں سن رہا ہوں۔ آپ کو کیا چاہیے؟',
      'greeting3': 'جی، بتائیے کیا آپ کرنا چاہتے ہیں۔',
      'greeting4': 'میں یہاں ہوں۔ میں آپ کی کیسے مدد کر سکتا ہوں؟',
      'greeting5': 'میں آپ کے لیے کیا کر سکتا ہوں؟',
      'greeting6': 'جی، آگے بڑھیں۔',
      'greeting7': 'سن رہا ہوں۔ آپ چاہتے ہیں کہ میں کیا کروں؟',
      'callConfirm': '{name} کو کال کر رہا ہے۔',
      'callSuccess': '{name} کو کال کر دی گئی۔',
      'callFailed': 'معاف کیجیے گا، میں {name} کو کال نہیں کر سکا۔',
      'messageSent': '{name} کو پیغام بھیج دیا گیا۔',
      'messageFailed': 'معاف کیجیے گا، میں پیغام نہیں بھیج سکا۔',
      'alarmSet': '{time} {date} کے لیے الارم سیٹ کر دیا گیا۔',
      'alarmFailed': 'معاف کیجیے گا، میں الارم سیٹ نہیں کر سکا۔',
      'reminderSet': '{title} کے لیے {time} {date} یاد دہانی سیٹ کر دی گئی۔',
      'reminderFailed': 'معاف کیجیے گا، میں یاد دہانی سیٹ نہیں کر سکا۔',
      'eventAdded': 'ایونٹ شامل کر دیا گیا: {title} {time} {date} کو۔',
      'eventDeleted': '{date} کے لیے ایونٹ حذف کر دیا گیا۔',
      'timeNow': 'وقت {time} ہے۔',
      'scheduleToday': 'آج کے لیے آپ کے {count} ایونٹس ہیں۔',
      'nextMeeting': 'آپ کا اگلا میٹنگ {title} {time} پر ہے۔',
      'noEvents': 'کوئی ایونٹ نہیں ملا۔',
      'navigation': '{screen} کھول رہا ہے۔',
      'unknownCommand': 'میں اس حکم کو نہیں سمجھا۔',
      'askContactName': 'آپ کون کال کرنا چاہتے ہیں؟',
      'askMessageText': 'میں کیا پیغام بھیجواں؟',
      'askTime': 'میں اسے کس وقت سیٹ کروں؟',
      'askTitle': 'میں آپ کو کیا یاد دلاؤں؟',
    },
    'roman_ur': {
      'initialGreeting': 'Assalam o Alaikum! Mic dabayen ya apna phone hilayen bolne ke liye.',
      'listening': 'Sun raha hai...',
      'processing': 'Process ho raha hai...',
      'didntHear': 'Maine kuch nahi suna.',
      'microphoneError': 'Microphone mein error ya permission nahi di gayi.',
      'cancelled': 'Theek hai, cancel kar diya gaya.',
      'yesNoPrompt': 'Please yes ya no kahein. Kya aap aage barhna chahte hain?',
      'greeting1': 'Ji? Main aapki kya madad kar sakta hoon?',
      'greeting2': 'Main sun raha hoon. Aapko kya chahiye?',
      'greeting3': 'Ji, batayiye kya aap karna chahte hain.',
      'greeting4': 'Main yahan hoon. Main aapki kaise madad kar sakta hoon?',
      'greeting5': 'Main aapke liye kya kar sakta hoon?',
      'greeting6': 'Ji, aage badhein.',
      'greeting7': 'Sun raha hoon. Aap chahte hain ke main kya karun?',
      'callConfirm': '{name} ko call kar raha hai.',
      'callSuccess': '{name} ko call kar di gayi.',
      'callFailed': 'Maaf kijiye ga, main {name} ko call nahi kar saka.',
      'messageSent': '{name} ko message bhej diya gaya.',
      'messageFailed': 'Maaf kijiye ga, main message nahi bhej saka.',
      'alarmSet': '{time} {date} ke liye alarm set kar diya gaya.',
      'alarmFailed': 'Maaf kijiye ga, main alarm set nahi kar saka.',
      'reminderSet': '{title} ke liye {time} {date} yaad dahani set kar di gayi.',
      'reminderFailed': 'Maaf kijiye ga, main yaad dahani set nahi kar saka.',
      'eventAdded': 'Event shamil kar diya gaya: {title} {time} {date} ko.',
      'eventDeleted': '{date} ke liye event delete kar diya gaya.',
      'timeNow': 'Waqt {time} hai.',
      'scheduleToday': 'Aaj ke liye aapke {count} events hain.',
      'nextMeeting': 'Aapka agla meeting {title} {time} par hai.',
      'noEvents': 'Koi event nahi mila.',
      'navigation': '{screen} khol raha hai.',
      'unknownCommand': 'Maine is command ko nahi samjha.',
      'askContactName': 'Aap koon call karna chahte hain?',
      'askMessageText': 'Main kya message bhejaun?',
      'askTime': 'Main use kis time set karun?',
      'askTitle': 'Main aapko kya yaad dilaaun?',
    },
  };

  static String getResponse(String language, String key) {
    return responses[language]?[key] ?? responses['en']?[key] ?? key;
  }

  static String getFormattedResponse(String language, String key, Map<String, String> params) {
    String template = getResponse(language, key);
    params.forEach((paramKey, value) {
      template = template.replaceAll('{$paramKey}', value);
    });
    return template;
  }
}