class LocalizedResponses {
  static Map<String, Map<String, String>> responses = {
    'en': {
      'initialGreeting': 'Shake your phone or tap the screen. Tell me what you want to do.',
      'listening': 'Listening...',
      'processing': 'Processing...',
      'didntHear': 'I didn\'t hear anything.',
      'pleaseRepeat': 'Sorry, I didn\'t catch that clearly. Please speak slowly and say it again.',
      'microphoneError': 'Microphone error or permission denied.',
      'cancelled': 'Okay, cancelled.',
      'yesNoPrompt': 'Please say Yes or No. Do you want to proceed?',
      'greeting1': 'What would you like me to do? You can call, send a message, or set an alarm.',
      'greeting2': 'I\'m listening. Say call, message, or alarm.',
      'greeting3': 'Tell me what you want to do.',
      'greeting4': 'I\'m here. Who should I call, message, or what alarm should I set?',
      'greeting5': 'What can I do for you?',
      'greeting6': 'Go ahead. Call, message, or alarm.',
      'greeting7': 'Listening. What would you like me to do?',
      'callConfirm': 'Calling {name}.',
      'callSuccess': 'Called {name}.',
      'callFailed': 'Sorry, I couldn\'t call {name}.',
      'messageSent': 'Message sent to {name}.',
      'messageFailed': 'Sorry, I couldn\'t send the message.',
      'alarmSet': 'Alarm set for {time} {date}.',
      'alarmFailed': 'Sorry, I couldn\'t set the alarm.',
      'reminderSet': 'Reminder set for {title} at {time} {date}.',
      'reminderFailed': 'Sorry, I couldn\'t set the reminder.',
      'eventAdded': 'Event added: {title} at {time} {date}.',
      'eventDeleted': 'Event deleted for {date}.',
      'timeNow': 'The time is {time}.',
      'scheduleToday': 'You have {count} events today.',
      'nextMeeting': 'Your next meeting is {title} at {time}.',
      'noEvents': 'No events found.',
      'navigation': 'Opening {screen}.',
      'unknownCommand': 'I didn\'t understand. Please say call, message, or set alarm, then the contact or time.',
      'askContactName': 'Who do you want to call?',
      'askMessageText': 'What message should I send?',
      'askTime': 'What time should I set it for?',
      'askTitle': 'What should I remind you about?',
    },
    'ur': {
      'initialGreeting': 'فون ہلائیں یا اسکرین دبائیں۔ بتائیں آپ کیا کرنا چاہتے ہیں۔',
      'listening': 'سن رہا ہے...',
      'processing': 'پروسیس ہو رہا ہے...',
      'didntHear': 'میں کچھ نہیں سنا۔',
      'pleaseRepeat': 'معاف کیجیے، بات واضح نہیں آئی۔ براہ کرم آہستہ اور دوبارہ کہیں۔',
      'microphoneError': 'مائیکروفون میں خرابی یا اجازت نہیں دی گئی۔',
      'cancelled': 'ٹھیک ہے، منسوخ کر دیا گیا۔',
      'yesNoPrompt': 'براہ کرم ہاں یا نہیں کہیں۔ کیا آپ آگے بڑھنا چاہتے ہیں؟',
      'greeting1': 'آپ کیا کرنا چاہتے ہیں؟ کال، میسج، یا الارم۔',
      'greeting2': 'میں سن رہا ہوں۔ کال، میسج یا الارم کہیں۔',
      'greeting3': 'بتائیں آپ کیا کرنا چاہتے ہیں۔',
      'greeting4': 'میں یہاں ہوں۔ کس کو کال یا میسج کروں، یا کون سا الارم لگاؤں؟',
      'greeting5': 'میں آپ کے لیے کیا کر سکتا ہوں؟',
      'greeting6': 'آگے بڑھیں۔ کال، میسج یا الارم۔',
      'greeting7': 'سن رہا ہوں۔ آپ کیا چاہتے ہیں؟',
      'callConfirm': '{name} کو کال کر رہا ہے۔',
      'callSuccess': '{name} کو کال کر دی گئی۔',
      'callFailed': 'معاف کیجیے گا، میں {name} کو کال نہیں کر سکا۔',
      'messageSent': '{name} کو پیغام بھیج دیا گیا۔',
      'messageFailed': 'معاف کیجیے گا، میں پیغام نہیں بھیج سکا۔',
      'alarmSet': '{time} {date} کے لیے الارم سیٹ کر دیا گیا۔',
      'alarmFailed': 'معاف کیجیے گا، میں الارم سیٹ نہیں کر سکا۔',
      'reminderSet': '{title} کے لیے {time} {date} یاد دہانی سیٹ کر دی گئی۔',
      'reminderFailed': 'معاف کیجیے گا، میں یاد دہانی سیٹ نہیں کر سکا۔',
      'eventAdded': 'ایونٹ شامل کر دیا گیا: {title} {time} {date} کو۔',
      'eventDeleted': '{date} کے لیے ایونٹ حذف کر دیا گیا۔',
      'timeNow': 'وقت {time} ہے۔',
      'scheduleToday': 'آج کے لیے آپ کے {count} ایونٹس ہیں۔',
      'nextMeeting': 'آپ کا اگلا میٹنگ {title} {time} پر ہے۔',
      'noEvents': 'کوئی ایونٹ نہیں ملا۔',
      'navigation': '{screen} کھول رہا ہے۔',
      'unknownCommand': 'سمجھ نہیں آیا۔ کال، میسج یا الارم کہیں، پھر نام یا وقت بتائیں۔',
      'askContactName': 'آپ کون کال کرنا چاہتے ہیں؟',
      'askMessageText': 'میں کیا پیغام بھیجواں؟',
      'askTime': 'میں اسے کس وقت سیٹ کروں؟',
      'askTitle': 'میں آپ کو کیا یاد دلاؤں؟',
    },
    'roman_ur': {
      'initialGreeting': 'Phone hilayein ya screen dabayein. Batayein aap kya karna chahte hain.',
      'listening': 'Sun raha hai...',
      'processing': 'Process ho raha hai...',
      'didntHear': 'Maine kuch nahi suna.',
      'pleaseRepeat': 'Maaf kijiye, baat clear nahi aayi. Please ahista aur dobara kahein.',
      'microphoneError': 'Microphone mein error ya permission nahi di gayi.',
      'cancelled': 'Theek hai, cancel kar diya gaya.',
      'yesNoPrompt': 'Please yes ya no kahein. Kya aap aage barhna chahte hain?',
      'greeting1': 'Aap kya karna chahte hain? Call, message, ya alarm.',
      'greeting2': 'Main sun raha hoon. Call, message ya alarm kahein.',
      'greeting3': 'Batayein aap kya karna chahte hain.',
      'greeting4': 'Main yahan hoon. Kisko call ya message karun, ya kaunsa alarm lagaoon?',
      'greeting5': 'Main aapke liye kya kar sakta hoon?',
      'greeting6': 'Aage badhein. Call, message ya alarm.',
      'greeting7': 'Sun raha hoon. Aap kya chahte hain?',
      'callConfirm': '{name} ko call kar raha hai.',
      'callSuccess': '{name} ko call kar di gayi.',
      'callFailed': 'Maaf kijiye ga, main {name} ko call nahi kar saka.',
      'messageSent': '{name} ko message bhej diya gaya.',
      'messageFailed': 'Maaf kijiye ga, main message nahi bhej saka.',
      'alarmSet': '{time} {date} ke liye alarm set kar diya gaya.',
      'alarmFailed': 'Maaf kijiye ga, main alarm set nahi kar saka.',
      'reminderSet': '{title} ke liye {time} {date} yaad dahani set kar di gayi.',
      'reminderFailed': 'Maaf kijiye ga, main yaad dahani set nahi kar saka.',
      'eventAdded': 'Event shamil kar diya gaya: {title} {time} {date} ko.',
      'eventDeleted': '{date} ke liye event delete kar diya gaya.',
      'timeNow': 'Waqt {time} hai.',
      'scheduleToday': 'Aaj ke liye aapke {count} events hain.',
      'nextMeeting': 'Aapka agla meeting {title} {time} par hai.',
      'noEvents': 'Koi event nahi mila.',
      'navigation': '{screen} khol raha hai.',
      'unknownCommand': 'Samajh nahi aaya. Call, message ya alarm kahein, phir naam ya time batayein.',
      'askContactName': 'Aap koon call karna chahte hain?',
      'askMessageText': 'Main kya message bhejaun?',
      'askTime': 'Main use kis time set karun?',
      'askTitle': 'Main aapko kya yaad dilaaun?',
    },
  };

  static String getResponse(String language, String key) {
    return responses[language]?[key] ?? responses['en']?[key] ?? key;
  }

  static String getFormattedResponse(String language, String key, Map<String, String> params) {
    String template = getResponse(language, key);
    params.forEach((paramKey, value) {
      template = template.replaceAll('{$paramKey}', value);
    });
    return template;
  }
}